// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzZCstE5ovQzlzuFFePg2-mLZquea1SRk',
    appId: '1:176857795462:web:2e073093832ae9a2ce3a07',
    messagingSenderId: '176857795462',
    projectId: 'flutter-486f2',
    authDomain: 'flutter-486f2.firebaseapp.com',
    storageBucket: 'flutter-486f2.firebasestorage.app',
    measurementId: 'G-K362M99XRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABaTVFXo5qZ2TmOQ5YPOyW5ARu4B7GJY8',
    appId: '1:176857795462:android:b9615696d3b2328ece3a07',
    messagingSenderId: '176857795462',
    projectId: 'flutter-486f2',
    storageBucket: 'flutter-486f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv654Wa-38KgQxxdNeFLf-w95vQrGx_98',
    appId: '1:176857795462:ios:c82550046d4adbb3ce3a07',
    messagingSenderId: '176857795462',
    projectId: 'flutter-486f2',
    storageBucket: 'flutter-486f2.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv654Wa-38KgQxxdNeFLf-w95vQrGx_98',
    appId: '1:176857795462:ios:c82550046d4adbb3ce3a07',
    messagingSenderId: '176857795462',
    projectId: 'flutter-486f2',
    storageBucket: 'flutter-486f2.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzZCstE5ovQzlzuFFePg2-mLZquea1SRk',
    appId: '1:176857795462:web:2af5e9dcd423d0c3ce3a07',
    messagingSenderId: '176857795462',
    projectId: 'flutter-486f2',
    authDomain: 'flutter-486f2.firebaseapp.com',
    storageBucket: 'flutter-486f2.firebasestorage.app',
    measurementId: 'G-LPPRK70G4F',
  );

}